" Return to last edit position when opening files
autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

" Toggle line numbers with ctrl-n
nnoremap <C-n> :set relativenumber!<CR>

" When using tabs
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:•
set list
